server:
  port: 8081

spring:
  application:
    name: receiver-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/receiverdb
    username: receiver
    password: receiverpass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: receiver-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.receiver: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG